split_form: 'kfold'
scaling_method: 'standard'
n_splits: 5
shuffle: true
test_size: 0.1
val_size: 0.2
seed_number: 42

seq_size: 256
interval_size: 128

columns_used: 
- 'GR'
- 'RHOB'
- 'NPHI'
- 'DTC'

num_channels: 4